In [10]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

### **Bài tập 1**

In [11]:
import random 
random.seed(0)
%matplotlib inline

def load_data_from_file(fileName):
    data = np.genfromtxt(fileName, dtype=None, delimiter=",", skip_header=1)
    features_X = data[:,:3]
    sales_y = data[:,3]
    n = data.shape[0]
    features_X = np.hstack((np.ones((n,1)),features_X))
    return features_X, sales_y 

# Question 2 
path = '/Users/macbook/Documents/AIO2024/AIO2024-Exercise/Module4/Week3/advertising.csv'
features_X, _ = load_data_from_file(path)
print(features_X[:5,:])

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]]


In [12]:
_, sales_y = load_data_from_file(path)
print(sales_y.shape)

(200,)


### **Bài tập 2**

In [40]:
def create_individual(n=4, bound=10):
    individual = [random.uniform(-bound/2,bound/2) for _ in range(n)]
    return individual

In [14]:
individual = create_individual()
print(individual)

[3.4442185152504816, 2.5795440294030243, -0.79428419169155, -2.4108324970703663]


### **Bài tập 3**

In [15]:
features_X, sales_y = load_data_from_file(path)

def compute_loss(individual):
    theta = np.array(individual)
    y_hat = features_X.dot(theta) 
    loss = np.multiply((y_hat-sales_y), (y_hat-sales_y)).mean()
    return loss 

def compute_fitness(individual):
    loss = compute_loss(individual)
    fitness_value = 1 / (loss + 1)
    return fitness_value

In [16]:
individual = [4.09, 4.82, 3.1, 4.02]
fitness_score = compute_fitness(individual)
fitness_score

1.0185991537088997e-06

### **Bài tập 4**

In [17]:
def crossover(individual1, individual2, rate = 0.9):
    individual1_new = individual1.copy()
    individual2_new = individual2.copy()

    for i in range(len(individual1_new)):
        if random.random() > 0.9:
            individual1_new[i] = individual2[i]
            individual2_new[i] = individual1[i] 
    return individual1_new, individual2_new

In [19]:
# Question 5 
individual1 = [4.09, 4.82, 3.10, 4.02]
individual2 = [3.44, 2.57, -0.79, -2.41]

individual1, individual2 = crossover(individual1, individual2,2.0)
print("individual1: ", individual1)
print("individual2: ", individual2)

individual1:  [4.09, 4.82, 3.1, 4.02]
individual2:  [3.44, 2.57, -0.79, -2.41]


### **Bài tập 5**

In [37]:
def mutate(individual, rate = 0.05):
    individual_m = individual.copy()
    for i in range(len(individual_m)):
        r = random.random()
        if r > rate:
            individual_m[1] = r 
    return individual_m

In [39]:
# Question 6
before_individual = [4.09, 4.82, 3.10, 4.02]
after_individual = mutate(individual, 2.0)
print(before_individual==after_individual)

True


### **Bài tập 6**

In [41]:
def initializePopulation(m):
    population = [create_individual() for _ in range(m)]
    return population

### **Bài tập 7**

In [42]:
def selection(sorted_old_population, m=100):
    index1 = random.randint(0, m-1)
    while True:
        index2 = random.randint(0, m-1)
        if index1 != index2:
            break 
    individual_s = sorted_old_population[index1]
    if sorted_old_population[index2] > sorted_old_population[index1]:
        individual_s = sorted_old_population[index2] 
    return individual_s

### **Bài tập 8**

In [ ]:
def create_new_population(old_population, elitism=2, gen=1):
    m = len(old_population)
    sorted_population = sorted(old_population, key=compute_fitness)

    if gen%1 == 0:
        print("Best loss: ", compute_loss(sorted_population[m-1]), "with chromsome: ",
              sorted_population[m-1])
    new_population = []
    while len(new_population) < m-elitism: